"""phase7 notifications and cms tables

Revision ID: 667594ab073a
Revises: 618a8c43c27f
Create Date: 2026-09-18 08:00:07.129185

Also seeds the five legally-required policy pages (NFR-COM-001) with
placeholder body text — these MUST be replaced with real, legally
reviewed copy before launch; they exist here only so the storefront has
something to link to and the pages are demonstrably publishable.
"""
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '667594ab073a'
down_revision: Union[str, Sequence[str], None] = '618a8c43c27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_pages',
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('page_type', sa.String(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("page_type IN ('page', 'faq', 'policy')", name='ck_cms_pages_page_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('notifications_log',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'sms')", name='ck_notifications_log_channel'),
    sa.CheckConstraint("status IN ('sent', 'failed')", name='ck_notifications_log_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    cms_pages_table = sa.table(
        'cms_pages',
        sa.column('slug', sa.String),
        sa.column('title', sa.String),
        sa.column('body', sa.Text),
        sa.column('page_type', sa.String),
        sa.column('is_published', sa.Boolean),
        sa.column('published_at', sa.DateTime(timezone=True)),
    )
    now = datetime.now(UTC)
    op.bulk_insert(
        cms_pages_table,
        [
            {
                'slug': 'terms-and-conditions',
                'title': 'Terms & Conditions',
                'body': 'Placeholder terms and conditions for The Shatranj Heritage. '
                        'Replace with legally reviewed copy before launch.',
                'page_type': 'policy',
                'is_published': True,
                'published_at': now,
            },
            {
                'slug': 'privacy-policy',
                'title': 'Privacy Policy',
                'body': 'Placeholder privacy policy for The Shatranj Heritage. '
                        'Replace with legally reviewed copy before launch.',
                'page_type': 'policy',
                'is_published': True,
                'published_at': now,
            },
            {
                'slug': 'return-and-refund-policy',
                'title': 'Return & Refund Policy',
                'body': 'Placeholder return and refund policy for The Shatranj Heritage. '
                        'Replace with legally reviewed copy before launch.',
                'page_type': 'policy',
                'is_published': True,
                'published_at': now,
            },
            {
                'slug': 'shipping-policy',
                'title': 'Shipping Policy',
                'body': 'Placeholder shipping policy for The Shatranj Heritage. '
                        'Replace with legally reviewed copy before launch.',
                'page_type': 'policy',
                'is_published': True,
                'published_at': now,
            },
            {
                'slug': 'warranty-policy',
                'title': 'Warranty Policy',
                'body': 'Placeholder warranty policy for The Shatranj Heritage. '
                        'Replace with legally reviewed copy before launch.',
                'page_type': 'policy',
                'is_published': True,
                'published_at': now,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_log')
    op.drop_table('cms_pages')
    # ### end Alembic commands ###
