"""phase6 shipping rates table

Revision ID: 618a8c43c27f
Revises: 365af278d782
Create Date: 2026-09-18 06:34:47.829717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618a8c43c27f'
down_revision: Union[str, Sequence[str], None] = '365af278d782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rates',
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_weight_grams', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('per_kg_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('standard', 'express')", name='ck_shipping_rates_method'),
    sa.CheckConstraint("zone IN ('dhaka', 'outside_dhaka')", name='ck_shipping_rates_zone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone', 'method', name='uq_shipping_rates_zone_method')
    )
    # ### end Alembic commands ###

    # Seed defaults so checkout/order placement has real rates from
    # day one (BR-SHP-002); Phase 7's admin settings UI is how these
    # get tuned afterward, not this migration.
    shipping_rates_table = sa.table(
        'shipping_rates',
        sa.column('zone', sa.String),
        sa.column('method', sa.String),
        sa.column('base_rate', sa.Numeric),
        sa.column('base_weight_grams', sa.Integer),
        sa.column('per_kg_rate', sa.Numeric),
    )
    op.bulk_insert(
        shipping_rates_table,
        [
            {
                'zone': 'dhaka', 'method': 'standard',
                'base_rate': '60.00', 'base_weight_grams': 1000, 'per_kg_rate': '15.00',
            },
            {
                'zone': 'dhaka', 'method': 'express',
                'base_rate': '120.00', 'base_weight_grams': 1000, 'per_kg_rate': '25.00',
            },
            {
                'zone': 'outside_dhaka', 'method': 'standard',
                'base_rate': '100.00', 'base_weight_grams': 1000, 'per_kg_rate': '25.00',
            },
            {
                'zone': 'outside_dhaka', 'method': 'express',
                'base_rate': '180.00', 'base_weight_grams': 1000, 'per_kg_rate': '35.00',
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_rates')
    # ### end Alembic commands ###
