"""phase8 performance indexes

Revision ID: fd502a1a9ac5
Revises: 20d514a833a6
Create Date: 2026-09-19 04:08:56.415497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd502a1a9ac5'
down_revision: Union[str, Sequence[str], None] = '20d514a833a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_product_variant_id'), table_name='inventory_transactions')
    op.create_index('ix_inventory_transactions_variant_created_at', 'inventory_transactions', ['product_variant_id', 'created_at'], unique=False)
    op.create_index('ix_orders_customer_id_placed_at', 'orders', ['customer_id', 'placed_at'], unique=False)
    op.create_index('ix_orders_status_placed_at', 'orders', ['status', 'placed_at'], unique=False)
    op.create_index('ix_product_variants_attributes', 'product_variants', ['attributes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_variants_attributes', table_name='product_variants', postgresql_using='gin')
    op.drop_index('ix_orders_status_placed_at', table_name='orders')
    op.drop_index('ix_orders_customer_id_placed_at', table_name='orders')
    op.drop_index('ix_inventory_transactions_variant_created_at', table_name='inventory_transactions')
    op.create_index(op.f('ix_inventory_transactions_product_variant_id'), 'inventory_transactions', ['product_variant_id'], unique=False)
    # ### end Alembic commands ###
