"""phase3 full text search and featured products

Revision ID: 5ed60d1b75f0
Revises: 8ea751b953c3
Create Date: 2026-09-17 15:47:22.909874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ed60d1b75f0'
down_revision: Union[str, Sequence[str], None] = '8ea751b953c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(name, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B')", persisted=True), nullable=False))
    op.create_index('ix_products_search_vector', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_search_vector', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'search_vector')
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
